;;; org-calendar-auto-test.el -*- lexical-binding: t; -*-
(load (expand-file-name "org-workflow-test.el" (file-name-directory load-file-name)) nil t)
(require 'org-gcal)
(load (expand-file-name "../lisp/org-calendar-auto.el" (file-name-directory load-file-name)) nil t)

(defvar my/calendar-test-server nil)
(defvar my/calendar-test-calls nil)
(defvar my/calendar-test-lost-reply nil)

(defun my/calendar-test-event (payload id etag)
  (let ((data (json-parse-string (json-encode payload) :object-type 'plist :array-type 'list)))
    (append (list :id id :etag etag) data)))

(defun my/calendar-test-request (method id payload etag callback &optional _params)
  (push (list method id payload etag) my/calendar-test-calls)
  (let ((existing (and id (gethash id my/calendar-test-server))))
    (cond
     ((and (equal method "GET") (null id))
      (funcall callback 200 (list :items (hash-table-values my/calendar-test-server))))
     ((equal method "GET") (funcall callback (if existing 200 404) existing))
     ((equal method "POST")
      (let* ((new-id (alist-get 'id payload))
             (event (my/calendar-test-event payload new-id "v1")))
        (puthash new-id event my/calendar-test-server)
        (if my/calendar-test-lost-reply
            (progn (setq my/calendar-test-lost-reply nil) (funcall callback nil nil))
          (funcall callback 200 event))))
     ((not (equal etag (plist-get existing :etag))) (funcall callback 412 nil))
     ((equal method "PATCH")
      (let ((event (my/calendar-test-event payload id "v2")))
        (dolist (key '(:recurringEventId :originalStartTime))
          (when (plist-member existing key)
            (setq event (plist-put event key (plist-get existing key)))))
        (puthash id event my/calendar-test-server)
        (funcall callback 200 event)))
     ((equal method "DELETE")
       (puthash id (append (list :id id :etag "deleted" :status "cancelled")
                           (when (plist-get existing :recurringEventId)
                             (list :recurringEventId (plist-get existing :recurringEventId)
                                   :originalStartTime (plist-get existing :originalStartTime)))) my/calendar-test-server)
      (funcall callback 204 nil))
     (t (ert-fail "Unexpected API operation")))))

(defmacro my/calendar-test-workspace (&rest body)
  (declare (indent 0))
  `(my/org-test-workspace
     (let* ((my/org-gcal-test-calendar-id "test@group.calendar.google.com")
            (my/org-calendar-auto--calendar my/org-gcal-test-calendar-id)
            (my/org-calendar-auto--file (my/org-file "calendar-personal.org"))
            (my/org-calendar-auto-mode t)
            (my/org-calendar-auto--busy nil)
            (my/org-calendar-auto--rerun nil)
            (my/org-calendar-auto--saving nil)
            (my/org-calendar-auto--attention nil)
            (my/org-calendar-auto--generation 1)
            (my/org-calendar-auto-status "pending")
            (my/org-calendar-settings-file (expand-file-name "settings.el" org-directory))
            (my/org-calendar-repeat--context nil)
            (my/org-calendar-repeat--events nil)
            (my/org-calendar-repeat--pending nil)
            (my/org-calendar-repeat--last-backup nil)
            (org-gcal--sync-lock nil)
            (my/calendar-test-server (make-hash-table :test 'equal))
            (my/calendar-test-calls nil)
            (my/calendar-test-lost-reply nil))
       (cl-letf (((symbol-function 'my/org-calendar-auto--request) #'my/calendar-test-request)
                 ((symbol-function 'my/org-calendar-auto--refresh-agendas) #'ignore)
                 ((symbol-function 'my/org-calendar-auto--schedule) #'ignore)
                 ((symbol-function 'run-at-time)
                  (lambda (_time _repeat function &rest args) (apply function args))))
         ,@body))))

(defun my/calendar-test-heading (text)
  (with-current-buffer (find-file-noselect my/org-calendar-auto--file)
    (goto-char (point-max))
    (insert "\n* " text "\n:org-gcal:\n<2026-10-12 Mon 10:00>--<2026-10-12 Mon 11:00>\n:END:\n")
    (org-back-to-heading t)
    (let ((marker (point-marker))) (save-buffer) marker)))

(ert-deftest my/calendar-auto-create-is-idempotent-after-lost-reply ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Create automatically")))
      (setq my/calendar-test-lost-reply t)
      (my/org-calendar-auto--start)
      (should (equal my/org-calendar-auto-status "pending"))
      (my/org-calendar-auto--start)
      (should (= (hash-table-count my/calendar-test-server) 1))
      (should (= (cl-count "POST" my/calendar-test-calls :key #'car :test #'equal) 1))
      (org-with-point-at marker
        (should (org-entry-get nil "entry-id"))
        (should (org-entry-get nil "GCAL_AUTO_BASE")))
      (should (equal my/org-calendar-auto-status "up to date")))))

(ert-deftest my/calendar-auto-local-edit-and-cancel ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Initial title")))
      (my/org-calendar-auto--start)
      (org-with-point-at marker (org-edit-headline "Updated title") (save-buffer))
      (my/org-calendar-auto--start)
      (should (equal (plist-get (car (hash-table-values my/calendar-test-server)) :summary) "Updated title"))
      (org-with-point-at marker (org-todo "CANCELLED") (save-buffer))
      (my/org-calendar-auto--start)
      (should (equal (plist-get (car (hash-table-values my/calendar-test-server)) :status) "cancelled"))
      (should (equal (nth 3 (car my/calendar-test-calls)) "v2"))
      (org-with-point-at marker (should (equal (org-get-todo-state) "CANCELLED"))))))

(ert-deftest my/calendar-auto-google-edit-and-cancel-retains-heading ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Initial title")))
      (my/org-calendar-auto--start)
      (let* ((event (car (hash-table-values my/calendar-test-server))) (id (plist-get event :id)))
        (puthash id (plist-put (plist-put (copy-tree event) :summary "Google title") :etag "google-v2") my/calendar-test-server)
        (my/org-calendar-auto--start)
        (org-with-point-at marker (should (equal (org-get-heading t t t t) "Google title")))
        (puthash id (list :id id :etag "google-v3" :status "cancelled") my/calendar-test-server)
        (my/org-calendar-auto--start)
        (org-with-point-at marker
          (should (equal (org-get-todo-state) "CANCELLED"))
          (should (equal (org-get-heading t t t t) "Google title")))))))

(ert-deftest my/calendar-auto-conflict-preserves-both-versions-and-resolves ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Initial title")))
      (my/org-calendar-auto--start)
      (org-with-point-at marker (org-edit-headline "Org choice") (save-buffer))
      (let* ((event (car (hash-table-values my/calendar-test-server))) (id (plist-get event :id)))
        (puthash id (plist-put (plist-put (copy-tree event) :summary "Google choice") :etag "google-v2") my/calendar-test-server)
        (my/org-calendar-auto--start)
        (org-with-point-at marker
          (should (equal (org-get-heading t t t t) "Org choice"))
          (should (equal (plist-get (my/org-calendar-auto--decode (org-entry-get nil "GCAL_AUTO_CONFLICT")) :summary)
                         "Google choice")))
        (should (equal my/org-calendar-auto-status "needs attention"))
        (my/org-calendar-auto--resolve marker "org")
        (my/org-calendar-auto--start)
        (should (equal (plist-get (gethash id my/calendar-test-server) :summary) "Org choice"))
        (org-with-point-at marker
          (should-not (org-entry-get nil "GCAL_AUTO_CONFLICT"))
          (should (org-entry-get nil "GCAL_AUTO_PREVIOUS")))))))

(ert-deftest my/calendar-auto-unsaved-edits-are-never-sent ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Saved title")))
      (org-with-point-at marker (org-edit-headline "Unsaved title"))
      (my/org-calendar-auto--start)
      (should-not my/calendar-test-calls)
      (should (equal my/org-calendar-auto-status "pending")))))

(ert-deftest my/calendar-auto-local-heading-deletion-never-deletes-google ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Keep Google copy")))
      (my/org-calendar-auto--start)
      (org-with-point-at marker (delete-region (point) (point-max)) (save-buffer))
      (setq my/calendar-test-calls nil)
      (my/org-calendar-auto--start)
      (should-not (cl-find "DELETE" my/calendar-test-calls :key #'car :test #'equal))
      (should (= (hash-table-count my/calendar-test-server) 1)))))

(ert-deftest my/calendar-auto-window-is-not-a-deletion-signal ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Outside polling window"))
          (server-request (symbol-function 'my/calendar-test-request)))
      (my/org-calendar-auto--start)
      (cl-letf (((symbol-function 'my/org-calendar-auto--request)
                 (lambda (method id payload etag callback &optional params)
                   (if (and (equal method "GET") (null id)) (funcall callback 200 '(:items nil))
                     (funcall server-request method id payload etag callback params)))))
        (my/org-calendar-auto--start))
      (org-with-point-at marker (should-not (org-get-todo-state)))
      (should-not (cl-find "DELETE" my/calendar-test-calls :key #'car :test #'equal)))))

(ert-deftest my/calendar-auto-all-day-ends-are-exclusive-and-dst-safe ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "All day")))
      (org-with-point-at marker
        (let ((drawer (my/org-calendar-auto--drawer)))
          (goto-char (car drawer))
          (delete-region (nth 0 drawer) (nth 1 drawer))
          (insert ":org-gcal:\n<2026-10-12 Mon>--<2026-10-14 Wed>\n:END:\n")
          (org-back-to-heading t))
        (let ((payload (my/org-calendar-auto--local-payload)))
          (should (equal (alist-get 'date (alist-get 'start payload)) "2026-10-12"))
          (should (equal (alist-get 'date (alist-get 'end payload)) "2026-10-15"))))
      (should (equal (my/org-calendar-auto--timestamp '(:start (:date "2026-10-12") :end (:date "2026-10-15")))
                     "<2026-10-12>--<2026-10-14>"))
      (should (equal (my/org-calendar-auto--day 2026 12 31 1) "2027-01-01")))))

(ert-deftest my/calendar-auto-all-day-capture-produces-date-only-google-event ()
  (my/calendar-test-workspace
    (let ((dates (list (encode-time 0 0 0 12 10 2026) (encode-time 0 0 0 12 10 2026))))
      (cl-letf (((symbol-function 'org-read-date) (lambda (&rest _) (pop dates))))
        (save-window-excursion
          (org-capture nil "pa")
          (insert "Captured all-day event")
          (org-capture-finalize))))
    (my/org-calendar-auto--start)
    (let ((event (car (hash-table-values my/calendar-test-server))))
      (should (equal (plist-get event :summary) "Captured all-day event"))
      (should (equal (plist-get (plist-get event :start) :date) "2026-10-12"))
      (should (equal (plist-get (plist-get event :end) :date) "2026-10-13"))
       (should-not (plist-get (plist-get event :start) :dateTime)))))

(ert-deftest my/calendar-auto-duration-capture-saved-before-finalizing-syncs-once ()
  (my/calendar-test-workspace
    (let ((start (encode-time 0 30 23 31 12 2026)) (duration-calls 0))
      (cl-letf (((symbol-function 'org-read-date) (lambda (&rest _) start))
                ((symbol-function 'read-string)
                 (lambda (&rest _)
                   (should (= (cl-incf duration-calls) 1)) "1h30m")))
        (save-window-excursion
          (org-capture nil "pe")
          (insert "Overnight duration capture")
          (save-buffer)
          (org-capture-finalize)))
      (my/org-calendar-auto--start)
      (my/org-calendar-auto--start)
      (let ((event (car (hash-table-values my/calendar-test-server))))
        (should (equal (plist-get event :summary) "Overnight duration capture"))
        (should (equal (plist-get (plist-get event :start) :dateTime)
                       (format-time-string "%FT%TZ" start t)))
        (should (equal (plist-get (plist-get event :end) :dateTime)
                       (format-time-string "%FT%TZ" (time-add start (seconds-to-time 5400)) t))))
      (should (= (hash-table-count my/calendar-test-server) 1))
      (should (= (cl-count "POST" my/calendar-test-calls :key #'car :test #'equal) 1)))))

(ert-deftest my/calendar-auto-notes-outside-drawer-survive-import ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Meeting")))
      (org-with-point-at marker (goto-char (point-max)) (insert "Private notes outside event drawer.\n") (save-buffer))
      (my/org-calendar-auto--start)
      (let* ((event (car (hash-table-values my/calendar-test-server))) (id (plist-get event :id)))
        (puthash id (plist-put (plist-put (copy-tree event) :description "Shared details") :etag "v2") my/calendar-test-server)
        (my/org-calendar-auto--start)
        (org-with-point-at marker
          (should (string-match-p "Private notes outside event drawer" (buffer-string)))
          (should (string-match-p "Shared details" (buffer-string))))))))

(ert-deftest my/calendar-auto-work-save-never-schedules-or-uploads ()
  (my/calendar-test-workspace
    (let (scheduled)
      (with-current-buffer (find-file-noselect (my/org-file "calendar-work.org"))
        (cl-letf (((symbol-function 'my/org-calendar-auto--schedule) (lambda (&rest _) (setq scheduled t))))
          (my/org-calendar-auto--after-save)))
      (should-not scheduled)
      (should-not my/calendar-test-calls))))

(ert-deftest my/calendar-auto-token-refresh-is-pending-not-another-login ()
  (my/calendar-test-workspace
    (let ((my/org-calendar-access-token nil)
          (my/org-calendar-token-expiration nil)
          (my/org-calendar-token-passphrase (copy-sequence "fake-unlock"))
          (my/org-calendar-auth-problem 'temporary)
          refreshed)
      (cl-letf (((symbol-function 'my/org-calendar-background-refresh) (lambda () (setq refreshed t))))
        (my/org-calendar-auto--start)
        (should refreshed)
        (should (equal my/org-calendar-auto-status "pending"))
        (my/org-calendar-auto--auth-finished nil t)
        (should (equal my/org-calendar-auto-status "pending"))
        (setq my/org-calendar-auth-problem 'authorization)
        (my/org-calendar-auto--auth-finished nil t)
        (should (equal my/org-calendar-auto-status "needs login"))))))

(ert-deftest my/calendar-auto-package-capture-hook-cannot-bypass-the-sync-queue ()
  (my/calendar-test-workspace
    (let ((org-capture-after-finalize-hook (list 'org-gcal--capture-post))
          (org-after-refile-insert-hook (list 'org-gcal--refile-post))
          (org-gcal-fetch-file-alist (list (cons my/org-calendar-auto--calendar my/org-calendar-auto--file)))
          (dates (list (encode-time 0 0 0 12 10 2026) (encode-time 0 0 0 12 10 2026)))
          (org/calendar-test-published nil))
      (cl-letf (((symbol-function 'org-read-date) (lambda (&rest _) (pop dates)))
                ((symbol-function 'org-gcal-post-at-point)
                 (lambda (&rest _) (setq org/calendar-test-published t))))
        (my/org-calendar-disable-package-auto-post)
        (should-not (memq 'org-gcal--capture-post org-capture-after-finalize-hook))
        ;; Simulate the package lazily registering its hook again after setup.
        (add-hook 'org-capture-after-finalize-hook 'org-gcal--capture-post)
        (save-window-excursion
          (org-capture nil "pa")
          (insert "One owner of publishing")
          (org-capture-finalize))
        (should-not org/calendar-test-published)
        (with-current-buffer (find-file-noselect my/org-calendar-auto--file)
          (should-not (buffer-modified-p)))
        (my/org-calendar-auto--start)
        (should (= (cl-count "POST" my/calendar-test-calls :key #'car :test #'equal) 1))))))

(ert-deftest my/calendar-auto-opening-agenda-checks-google-even-after-a-recent-sync ()
  (my/calendar-test-workspace
    (let ((my/org-calendar-auto--last-run (float-time))
          (my/org-calendar-auto--refreshing nil) scheduled)
      (with-temp-buffer
        (org-agenda-mode)
        (cl-letf (((symbol-function 'my/org-calendar-auto--schedule) (lambda (&rest _) (setq scheduled t))))
          (my/org-calendar-auto--agenda-open)))
      (should scheduled))))

(ert-deftest my/calendar-auto-manual-agenda-refresh-queues-sync-but-auto-redraw-does-not ()
  (my/calendar-test-workspace
    (let ((org-agenda-finalize-hook (list #'my/org-calendar-auto--agenda-open))
          (my/org-calendar-auto--refreshing nil)
          (scheduled 0))
      (save-window-excursion
        (cl-letf (((symbol-function 'my/org-calendar-auto--schedule) (lambda (&rest _) (cl-incf scheduled))))
          (org-agenda nil "d")
          (should (> scheduled 0))
          (setq scheduled 0)
          (org-agenda-redo)
          (should (> scheduled 0))
          (setq scheduled 0)
          (let ((my/org-calendar-auto--refreshing t)) (org-agenda-redo))
          (should (= scheduled 0)))))))

(ert-deftest my/calendar-auto-wrong-calendar-and-malformed-events-are-blocked ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Wrong calendar")))
      (org-with-point-at marker
        (org-entry-put nil "calendar-id" "other@group.calendar.google.com")
        (save-buffer))
      (my/org-calendar-auto--start)
      (should-not (cl-find "POST" my/calendar-test-calls :key #'car :test #'equal))
      (should (equal my/org-calendar-auto-status "needs attention"))
      (org-with-point-at marker (should (org-entry-get nil "GCAL_AUTO_ERROR"))))))

(ert-deftest my/calendar-auto-duplicate-identities-block-both-headings ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Original")))
      (my/org-calendar-auto--start)
      (org-with-point-at marker
        (let ((copy (buffer-substring-no-properties (point) (point-max))))
          (goto-char (point-max)) (insert "\n" copy) (save-buffer)))
      (setq my/calendar-test-calls nil)
      (my/org-calendar-auto--start)
      (should-not (cl-find-if (lambda (call) (member (car call) '("POST" "PATCH" "DELETE"))) my/calendar-test-calls))
      (should (equal my/org-calendar-auto-status "needs attention")))))

(ert-deftest my/calendar-auto-old-unlinked-cancellation-is-ignored ()
  (my/calendar-test-workspace
    (with-current-buffer (find-file-noselect my/org-calendar-auto--file)
      (goto-char (point-max)) (insert "\n* CANCELLED Old test\n") (save-buffer))
    (my/org-calendar-auto--start)
    (should (equal my/org-calendar-auto-status "up to date"))
    (should-not (cl-find "POST" my/calendar-test-calls :key #'car :test #'equal))))

(ert-deftest my/calendar-auto-newer-local-edits-survive-a-late-write-response ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Sent title")) reply returned
          (server-request (symbol-function 'my/calendar-test-request)))
      (cl-letf (((symbol-function 'my/org-calendar-auto--request)
                 (lambda (method id payload etag callback &optional params)
                   (if (equal method "POST")
                       (funcall server-request method id payload etag
                                (lambda (status data) (setq reply callback returned (list status data))) params)
                     (funcall server-request method id payload etag callback params)))))
        (my/org-calendar-auto--start)
        (org-with-point-at marker (org-edit-headline "Newer title") (save-buffer))
        (apply reply returned)
        (org-with-point-at marker
          (should (equal (org-get-heading t t t t) "Newer title"))
          (should-not (equal (org-entry-get nil "GCAL_AUTO_BASE")
                             (my/org-calendar-auto--hash (my/org-calendar-auto--local-payload)))))
        (should (equal my/org-calendar-auto-status "pending")))
      (my/org-calendar-auto--start)
      (should (equal (plist-get (car (hash-table-values my/calendar-test-server)) :summary) "Newer title")))))

(ert-deftest my/calendar-auto-a-new-google-change-invalidates-a-resolution ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Initial")))
      (my/org-calendar-auto--start)
      (org-with-point-at marker (org-edit-headline "Org change") (save-buffer))
      (let* ((event (car (hash-table-values my/calendar-test-server))) (id (plist-get event :id)))
        (puthash id (plist-put (plist-put (copy-tree event) :summary "Google change") :etag "v2") my/calendar-test-server)
        (my/org-calendar-auto--start)
        (my/org-calendar-auto--resolve marker "org")
        (puthash id (plist-put (plist-put (copy-tree event) :summary "Newer Google change") :etag "v3") my/calendar-test-server)
        (setq my/calendar-test-calls nil)
        (my/org-calendar-auto--start)
        (should-not (cl-find "PATCH" my/calendar-test-calls :key #'car :test #'equal))
        (org-with-point-at marker
          (should (equal (org-get-heading t t t t) "Org change"))
          (should-not (org-entry-get nil "GCAL_AUTO_RESOLUTION")))))))

(ert-deftest my/calendar-auto-http-adapter-is-async-and-uses-if-match ()
  (my/calendar-test-workspace
    (let (url options completed)
      (cl-letf (((symbol-function 'request)
                 (lambda (endpoint &rest args) (setq url endpoint options args)))
                ((symbol-function 'request-response-status-code) (lambda (_) 200)))
        ;; Bypass the fake server for this adapter test.
        (let ((adapter (with-temp-buffer
                         (insert-file-contents (expand-file-name "../lisp/org-calendar-auto.el"
                                                                (file-name-directory my/org-calendar-test-worker-file)))
                         (goto-char (point-min)) (search-forward "(defun my/org-calendar-auto--request")
                         (goto-char (match-beginning 0)) (read (current-buffer)))))
          (cl-letf (((symbol-function 'my/org-calendar-auto--request) (eval `(lambda ,@(cddr adapter)) t)))
            (my/org-calendar-auto--request "PATCH" "event-id" '((summary . "Title")) "etag-v1"
                                           (lambda (&rest _) (setq completed t)))))
        (should (string-match-p "/calendars/test%40group.calendar.google.com/events/event-id" url))
        (should-not (plist-get options :sync))
        (should (= (plist-get options :timeout) 20))
        (should (equal (cdr (assoc "If-Match" (plist-get options :headers))) "etag-v1"))
        (cl-incf my/org-calendar-auto--generation)
        (funcall (plist-get options :complete) :response 'fake :data '(:id "event-id"))
        (should-not completed)))))
