;;; org-calendar-repeat-test.el -*- lexical-binding: t; -*-
(load (expand-file-name "org-calendar-keychain-test.el" (file-name-directory load-file-name)) nil t)

(defun my/calendar-repeat-test-seed (&optional count)
  "Create one indefinite Google series and COUNT expanded test occurrences."
  (let* ((payload (org-with-point-at (my/calendar-test-heading "Series")
                    (prog1 (my/org-calendar-auto--local-payload)
                      (delete-region (point) (point-max)) (save-buffer))))
         (master (my/calendar-test-event payload "series" "master-v1")) events)
    (setq master (plist-put master :recurrence '("RRULE:FREQ=DAILY")))
    (setq master (plist-put master :start (plist-put (plist-get master :start) :timeZone "America/Sao_Paulo")))
    (setq master (plist-put master :end (plist-put (plist-get master :end) :timeZone "America/Sao_Paulo")))
    (puthash "series" master my/calendar-test-server)
    (dotimes (offset (or count 4))
      (let* ((id (format "series_%d" offset))
             (event (my/calendar-test-event payload id "instance-v1")))
        (dolist (key '(:start :end))
          (let ((instant (parse-iso8601-time-string (plist-get (plist-get event key) :dateTime))))
            (setq event (plist-put event key (list :dateTime (format-time-string "%FT%TZ" (time-add instant (days-to-time offset)) t))))))
        (setq event (plist-put event :recurringEventId "series"))
        (setq event (plist-put event :originalStartTime (copy-tree (plist-get event :start))))
        (puthash id event my/calendar-test-server)
        (push event events)))
    (nreverse events)))

(defun my/calendar-repeat-test-headings ()
  (with-current-buffer (my/org-calendar-auto--buffer)
    (org-map-entries (lambda () (org-get-heading t t t t)) nil 'file)))

(defun my/calendar-repeat-test-import (event)
  (let ((marker (my/calendar-test-heading "Old occurrence")))
    (org-with-point-at marker
      (my/org-calendar-auto--import (plist-get event :id) event) (save-buffer))
    marker))

(ert-deftest my/calendar-repeat-one-heading-with-indefinite-rule-and-no-spurious-writes ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed 20)
    (my/org-calendar-auto--start)
    (should (= (length (my/calendar-repeat-test-headings)) 1))
    (should (= (length my/org-calendar-repeat--events) 20))
    (org-with-point-at (my/org-calendar-repeat--series-marker "series")
      (should (equal (org-entry-get nil "recurrence") "[\"RRULE:FREQ=DAILY\"]"))
      (should (equal (my/org-calendar-auto--local-payload)
                     (my/org-calendar-auto--remote-payload (gethash "series" my/calendar-test-server)))))
    (setq my/calendar-test-calls nil)
    (my/org-calendar-auto--start)
    (should (equal my/org-calendar-auto-status "up to date"))
    (should-not (seq-some (lambda (call) (member (car call) '("POST" "PATCH" "DELETE"))) my/calendar-test-calls))))

(ert-deftest my/calendar-repeat-agenda-occurrences-point-to-live-series-marker ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (save-window-excursion
      (let ((org-agenda-start-day "2026-10-12") (org-agenda-span 7))
        (org-agenda-list))
      (with-current-buffer org-agenda-buffer-name
        (let ((count 0))
          (goto-char (point-min))
          (while (not (eobp))
            (when-let* ((event (org-get-at-bol 'my/org-calendar-repeat-event)))
              (cl-incf count)
              (let ((marker (org-get-at-bol 'org-hd-marker)))
                (should (buffer-live-p (marker-buffer marker)))
                (org-with-point-at marker (should (equal (org-entry-get nil "GCAL_AUTO_ID") "series"))))
              (should (equal (org-get-at-bol 'my/org-calendar-repeat-id) (plist-get event :id))))
            (forward-line))
          (should (= count 4)))))))

(ert-deftest my/calendar-repeat-clean-legacy-migration-is-backed-up-and-local-only ()
  (my/calendar-test-workspace
    (let ((events (my/calendar-repeat-test-seed)))
      (mapc #'my/calendar-repeat-test-import events)
      (should (= (length (my/calendar-repeat-test-headings)) 4))
      (my/org-calendar-auto--start)
      (should (= (length (my/calendar-repeat-test-headings)) 1))
      (should (file-exists-p my/org-calendar-repeat--last-backup))
      (should (= (logand (file-modes my/org-calendar-repeat--last-backup) #o777) #o600))
      (with-temp-buffer
        (insert-file-contents my/org-calendar-repeat--last-backup)
        (should (= (how-many "^\\* " (point-min) (point-max)) 4)))
      (should-not (seq-some (lambda (call) (member (car call) '("PATCH" "DELETE" "POST"))) my/calendar-test-calls)))))

(ert-deftest my/calendar-repeat-migration-retains-notes-custom-properties-and-conflicts ()
  (my/calendar-test-workspace
    (let ((events (my/calendar-repeat-test-seed)))
      (let ((notes (my/calendar-repeat-test-import (nth 0 events)))
            (custom (my/calendar-repeat-test-import (nth 1 events)))
            (conflict (my/calendar-repeat-test-import (nth 2 events))))
        (my/calendar-repeat-test-import (nth 3 events))
        (org-with-point-at notes
          (goto-char (nth 1 (my/org-calendar-auto--drawer))) (insert "\nPrivate note\n") (save-buffer))
        (org-with-point-at custom (org-entry-put nil "MY_NOTE" "keep me") (save-buffer))
        (org-with-point-at conflict
          (org-edit-headline "Unsent conflict version")
          (my/org-calendar-auto--conflict (plist-put (copy-tree (nth 2 events)) :summary "Other version")) (save-buffer))
        (my/org-calendar-auto--start)
        (should (= (length (my/calendar-repeat-test-headings)) 4))
        (with-current-buffer (my/org-calendar-auto--buffer) (should (string-match-p "Private note" (buffer-string))))
        (org-with-point-at custom (should (equal (org-entry-get nil "MY_NOTE") "keep me")))
        (should (my/org-calendar-repeat--series-marker "series"))
        (should (equal my/org-calendar-auto-status "needs attention"))))))

(ert-deftest my/calendar-repeat-migration-retains-pending-and-unsaved-edits ()
  (my/calendar-test-workspace
    (let* ((events (my/calendar-repeat-test-seed))
           (marker (my/calendar-repeat-test-import (car events))))
      (org-with-point-at marker (org-edit-headline "Pending edit") (save-buffer))
      (my/org-calendar-auto--start)
      (org-with-point-at marker (should (equal (org-entry-get nil "GCAL_AUTO_ID") "series_0")))
      (should (= (length (my/calendar-repeat-test-headings)) 2))
      (org-with-point-at marker (org-edit-headline "Unsaved"))
      (setq my/calendar-test-calls nil)
      (my/org-calendar-auto--start)
      (should-not my/calendar-test-calls))))

(ert-deftest my/calendar-repeat-cache-survives-restart-and-replaces-old-window ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (let ((file (my/org-calendar-repeat--cache-file)))
      (should (= (logand (file-modes file) #o777) #o600))
      (setq my/org-calendar-repeat--context nil my/org-calendar-repeat--events nil)
      (my/org-calendar-repeat--ensure-state)
      (should (= (length my/org-calendar-repeat--events) 4)))
    (remhash "series_0" my/calendar-test-server)
    (my/org-calendar-auto--start)
    (should (= (length my/org-calendar-repeat--events) 3))
    (should (= (length (my/calendar-repeat-test-headings)) 1))))

(ert-deftest my/calendar-repeat-moved-and-cancelled-exceptions-follow-google ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (let ((moved (gethash "series_1" my/calendar-test-server)))
      (setq moved (plist-put moved :start '(:dateTime "2026-10-13T18:00:00Z")))
      (setq moved (plist-put moved :end '(:dateTime "2026-10-13T19:00:00Z")))
      (puthash "series_1" moved my/calendar-test-server))
    (puthash "series_2" '(:id "series_2" :recurringEventId "series" :status "cancelled") my/calendar-test-server)
    (my/org-calendar-auto--start)
    (should (= (length (my/calendar-repeat-test-headings)) 1))
    (should (= (length (seq-remove (lambda (event) (equal (plist-get event :status) "cancelled"))
                                  my/org-calendar-repeat--events)) 3))
    (should (string-match-p "15:00" (my/org-calendar-auto--timestamp
                                    (seq-find (lambda (event) (equal (plist-get event :id) "series_1"))
                                              my/org-calendar-repeat--events))))))

(ert-deftest my/calendar-repeat-occurrence-edit-and-cancellation-never-write-master ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (let* ((event (gethash "series_1" my/calendar-test-server))
           (desired (plist-put (copy-tree event) :summary "Only Tuesday")))
      (my/org-calendar-repeat--queue event desired)
      (my/org-calendar-auto--start)
      (should (equal (plist-get (gethash "series_1" my/calendar-test-server) :summary) "Only Tuesday"))
      (should-not my/org-calendar-repeat--pending)
      (should (equal (plist-get (gethash "series" my/calendar-test-server) :etag) "master-v1")))
    (let ((event (gethash "series_2" my/calendar-test-server)))
      (my/org-calendar-repeat--queue event (plist-put (copy-tree event) :status "cancelled")))
    (my/org-calendar-auto--start)
    (should-not my/org-calendar-repeat--pending)
    (should (equal (plist-get (gethash "series_2" my/calendar-test-server) :status) "cancelled"))
    (should-not (seq-some (lambda (call) (and (equal (nth 1 call) "series")
                                            (member (car call) '("PATCH" "DELETE")))) my/calendar-test-calls))))

(ert-deftest my/calendar-repeat-series-writes-need-exact-saved-version-approval ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (let ((marker (my/org-calendar-repeat--series-marker "series")))
      (org-with-point-at marker (org-edit-headline "Whole series") (save-buffer))
      (my/org-calendar-auto--start)
      (should (equal (plist-get (gethash "series" my/calendar-test-server) :summary) "Series"))
      (should (equal my/org-calendar-auto-status "needs attention"))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (my/org-calendar-repeat--approve-series marker))
      (org-with-point-at marker (org-edit-headline "Newer unapproved") (save-buffer))
      (my/org-calendar-auto--start)
      (should (equal (plist-get (gethash "series" my/calendar-test-server) :summary) "Series"))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (my/org-calendar-repeat--approve-series marker))
      (my/org-calendar-auto--start)
      (should (equal (plist-get (gethash "series" my/calendar-test-server) :summary) "Newer unapproved"))
      (org-with-point-at marker (should-not (org-entry-get nil "GCAL_SERIES_APPROVED"))))))

(ert-deftest my/calendar-repeat-occurrence-conflict-is-persistent-and-newer-google-invalidates-choice ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (let ((event (gethash "series_1" my/calendar-test-server)))
      (my/org-calendar-repeat--queue event (plist-put (copy-tree event) :summary "Org choice"))
      (puthash "series_1" (plist-put (plist-put (copy-tree event) :summary "Google choice") :etag "new") my/calendar-test-server)
      (my/org-calendar-auto--start)
      (should (plist-get (car my/org-calendar-repeat--pending) :conflict))
      (setq my/org-calendar-repeat--context nil my/org-calendar-repeat--pending nil)
      (my/org-calendar-repeat--ensure-state)
      (should (equal (plist-get (plist-get (car my/org-calendar-repeat--pending) :desired) :summary) "Org choice"))
      (my/org-calendar-repeat--replace-job (plist-put (car my/org-calendar-repeat--pending) :resolution "org"))
      (puthash "series_1" (plist-put (gethash "series_1" my/calendar-test-server) :etag "newer") my/calendar-test-server)
      (my/org-calendar-auto--start)
      (should-not (plist-get (car my/org-calendar-repeat--pending) :resolution))
      (should (equal (plist-get (gethash "series_1" my/calendar-test-server) :summary) "Google choice")))))

(ert-deftest my/calendar-repeat-offline-queue-retains-edits-and-retries ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (let ((event (gethash "series_0" my/calendar-test-server)))
      (my/org-calendar-repeat--queue event (plist-put (copy-tree event) :summary "Offline edit")))
    (cl-letf (((symbol-function 'my/org-calendar-auto--request)
               (lambda (_method _id _payload _etag callback &optional _params) (funcall callback nil nil))))
      (my/org-calendar-auto--start))
    (should my/org-calendar-repeat--pending)
    (my/org-calendar-auto--start)
    (should-not my/org-calendar-repeat--pending)
    (should (equal (plist-get (gethash "series_0" my/calendar-test-server) :summary) "Offline edit"))))

(ert-deftest my/calendar-repeat-generic-agenda-date-edits-require-scope ()
  (my/calendar-test-workspace
    (with-temp-buffer
      (org-agenda-mode)
      (insert (propertize "Occurrence\n" 'my/org-calendar-repeat-event '(:id "x")))
      (goto-char (point-min))
      (should-error (org-agenda-date-later 1) :type 'user-error))))

(ert-deftest my/calendar-repeat-newer-local-edit-survives-late-occurrence-write ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (let* ((event (gethash "series_0" my/calendar-test-server))
           (adapter (symbol-function 'my/calendar-test-request)))
      (my/org-calendar-repeat--queue event (plist-put (copy-tree event) :summary "First edit"))
      (cl-letf (((symbol-function 'my/org-calendar-auto--request)
                 (lambda (method id payload etag callback &optional params)
                   (when (equal method "PATCH")
                     (my/org-calendar-repeat--queue event (plist-put (copy-tree event) :summary "Newer edit")))
                   (funcall adapter method id payload etag callback params))))
        (my/org-calendar-auto--start))
      (should (equal (plist-get (plist-get (car my/org-calendar-repeat--pending) :desired) :summary) "Newer edit"))
      (should (equal (plist-get (plist-get (car my/org-calendar-repeat--pending) :base) :etag) "v2"))
      (my/org-calendar-auto--start)
      (should-not my/org-calendar-repeat--pending)
      (should (equal (plist-get (gethash "series_0" my/calendar-test-server) :summary) "Newer edit")))))

(ert-deftest my/calendar-repeat-occurrence-412-reads-new-version-before-review ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (let* ((event (gethash "series_0" my/calendar-test-server))
           (adapter (symbol-function 'my/calendar-test-request)))
      (my/org-calendar-repeat--queue event (plist-put (copy-tree event) :summary "Org edit"))
      (cl-letf (((symbol-function 'my/org-calendar-auto--request)
                 (lambda (method id payload etag callback &optional params)
                   (when (equal method "PATCH")
                     (puthash id (plist-put (plist-put (copy-tree event) :summary "Racing Google edit")
                                          :etag "racing-etag") my/calendar-test-server))
                   (funcall adapter method id payload etag callback params))))
        (my/org-calendar-auto--start))
      (should (equal (plist-get (plist-get (car my/org-calendar-repeat--pending) :conflict) :etag) "racing-etag"))
      (should (equal (plist-get (plist-get (car my/org-calendar-repeat--pending) :desired) :summary) "Org edit")))))

(ert-deftest my/calendar-repeat-occurrence-editor-is-local-and-does-not-change-org-keymap ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (let ((cc (lookup-key org-mode-map (kbd "C-c C-c")))
          (ck (lookup-key org-mode-map (kbd "C-c C-k"))) editor)
      (unwind-protect
          (save-window-excursion
            (with-temp-buffer
              (org-agenda-mode)
              (insert (propertize "Occurrence\n" 'my/org-calendar-repeat-event (gethash "series_0" my/calendar-test-server)))
              (goto-char (point-min))
              (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "This occurrence")))
                (setq editor (my/org-calendar-repeat-edit))))
            (should (equal (lookup-key org-mode-map (kbd "C-c C-c")) cc))
            (should (equal (lookup-key org-mode-map (kbd "C-c C-k")) ck))
            (with-current-buffer editor
              (goto-char (point-min))
              (org-edit-headline "Only this occurrence")
              (call-interactively (lookup-key (current-local-map) (kbd "C-c C-c"))))
            (should (equal (plist-get (plist-get (car my/org-calendar-repeat--pending) :desired) :summary)
                           "Only this occurrence")))
        (when (buffer-live-p editor) (kill-buffer editor))))))

(ert-deftest my/calendar-repeat-agenda-cancel-asks-scope-and-preserves-unsaved-series ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (let ((marker (my/org-calendar-repeat--series-marker "series")))
      (with-temp-buffer
        (org-agenda-mode)
        (insert (propertize "Occurrence\n" 'org-hd-marker marker
                            'my/org-calendar-repeat-event (gethash "series_0" my/calendar-test-server)))
        (goto-char (point-min))
        (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Delete this occurrence"))
                  ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
          (org-agenda-todo))
        (should (= (length my/org-calendar-repeat--pending) 1))
        (org-with-point-at marker (should-not (org-get-todo-state)) (org-edit-headline "Unsaved series"))
        (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Delete entire series"))
                  ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
          (should-error (org-agenda-todo) :type 'user-error))
        (org-with-point-at marker (should (buffer-modified-p)) (should-not (org-get-todo-state)))))))

(ert-deftest my/calendar-repeat-all-day-series-keeps-inclusive-occurrence-range ()
  (my/calendar-test-workspace
    (let* ((payload '((summary . "All-day series") (start . ((date . "2026-10-12")))
                     (end . ((date . "2026-10-15"))) (description . "")
                     (location . "") (transparency . "opaque") (status . "confirmed")))
           (master (my/calendar-test-event payload "series" "v1"))
           (event (my/calendar-test-event payload "occurrence" "v1")))
      (puthash "series" (plist-put master :recurrence '("RRULE:FREQ=WEEKLY")) my/calendar-test-server)
      (puthash "occurrence" (plist-put event :recurringEventId "series") my/calendar-test-server)
      (my/org-calendar-auto--start)
      (should (= (length (my/calendar-repeat-test-headings)) 1))
      (should (equal (my/org-calendar-auto--timestamp (car my/org-calendar-repeat--events))
                     "<2026-10-12>--<2026-10-14>")))))

(ert-deftest my/calendar-repeat-delete-menu-defaults-to-keeping-the-event ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (with-temp-buffer
      (org-agenda-mode)
      (insert (propertize "Occurrence\n" 'org-hd-marker (my/org-calendar-repeat--series-marker "series")
                          'my/org-calendar-repeat-event (gethash "series_0" my/calendar-test-server)))
      (goto-char (point-min))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (prompt choices _predicate _required _initial _history default &rest _)
                   (should (string-match-p (regexp-quote "Google + agenda") prompt))
                   (should (equal default "Keep event"))
                   (should (member "Delete this occurrence" choices))
                   (should (member "Delete entire series" choices))
                   default))
                ((symbol-function 'yes-or-no-p) (lambda (&rest _) (ert-fail "Keeping needs no deletion prompt"))))
        (org-agenda-todo))
      (should-not my/org-calendar-repeat--pending)
      (org-with-point-at (org-get-at-bol 'org-hd-marker)
        (should-not (org-get-todo-state))
        (should-not (buffer-modified-p))))))

(ert-deftest my/calendar-repeat-deletion-confirmation-states-date-destination-and-scope ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (with-temp-buffer
      (org-agenda-mode)
      (insert (propertize "Occurrence\n" 'org-hd-marker (my/org-calendar-repeat--series-marker "series")
                          'my/org-calendar-repeat-event (gethash "series_0" my/calendar-test-server)))
      (goto-char (point-min))
      (dolist (choice '("Delete this occurrence" "Delete entire series"))
        (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) choice))
                  ((symbol-function 'yes-or-no-p)
                   (lambda (prompt)
                     (should (string-match-p "Google and the agenda" prompt))
                     (should (string-match-p "Series" prompt))
                     (if (equal choice "Delete this occurrence")
                         (progn
                           (should (string-match-p "2026-10-12" prompt))
                           (should (string-match-p "Other occurrences stay unchanged" prompt)))
                       (should (string-match-p "ALL occurrences" prompt)))
                     nil)))
          (org-agenda-todo))
        (should-not my/org-calendar-repeat--pending)
        (org-with-point-at (org-get-at-bol 'org-hd-marker)
          (should-not (org-get-todo-state))
          (should-not (buffer-modified-p)))))))

(ert-deftest my/calendar-repeat-task-state-command-does-not-show-calendar-prompts ()
  (my/calendar-test-workspace
    (with-current-buffer (find-file-noselect (my/org-file "work.org"))
      (goto-char (point-max)) (insert "\n* TODO Ordinary work task\n") (save-buffer))
    (save-window-excursion
      (org-agenda nil "r")
      (with-current-buffer org-agenda-buffer-name
        (goto-char (point-min)) (search-forward "Ordinary work task") (beginning-of-line)
        (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (ert-fail "Unexpected calendar menu for a task")))
                  ((symbol-function 'yes-or-no-p) (lambda (&rest _) (ert-fail "Unexpected deletion confirmation for a task"))))
          (org-agenda-todo "DOING"))
        (org-with-point-at (org-get-at-bol 'org-hd-marker)
          (should (equal (org-get-todo-state) "DOING")))))
    (should-not my/org-calendar-repeat--pending)))

(ert-deftest my/calendar-repeat-task-default-state-selector-is-passed-through-unchanged ()
  (with-temp-buffer
    (org-agenda-mode)
    (insert "Ordinary task\n") (goto-char (point-min))
    (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (ert-fail "Unexpected calendar menu")))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) (ert-fail "Unexpected deletion prompt"))))
      (should (equal (my/org-calendar-repeat--todo (lambda (&rest arguments) (cons 'task-selector arguments)))
                     '(task-selector)))
      (should (equal (my/org-calendar-repeat--todo (lambda (&rest arguments) arguments) "WAIT" 'prefix)
                     '("WAIT" prefix))))))

(ert-deftest my/calendar-repeat-lost-occurrence-reply-retries-without-duplicate-write ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (let* ((event (gethash "series_0" my/calendar-test-server))
           (adapter (symbol-function 'my/calendar-test-request)))
      (my/org-calendar-repeat--queue event (plist-put (copy-tree event) :summary "Lost reply"))
      (cl-letf (((symbol-function 'my/org-calendar-auto--request)
                 (lambda (method id payload etag callback &optional params)
                   (funcall adapter method id payload etag
                            (if (equal method "PATCH") (lambda (&rest _) (funcall callback nil nil)) callback)
                            params))))
        (my/org-calendar-auto--start))
      (should my/org-calendar-repeat--pending)
      (my/org-calendar-auto--start)
      (should-not my/org-calendar-repeat--pending)
      (should (= (cl-count "PATCH" my/calendar-test-calls :key #'car :test #'equal) 1)))))

(ert-deftest my/calendar-review-title-only-conflict-hides-api-metadata-and-equivalent-timezones ()
  (let* ((local '((summary . "Sextou offline")
                  (start . ((dateTime . "2026-10-09T22:00:00Z")))
                  (end . ((dateTime . "2026-10-09T23:00:00Z")))
                  (description . "") (location . "") (transparency . "opaque") (status . "confirmed")))
         (remote '(:summary "Sextou online" :id "private-event-id" :etag "private-etag"
                   :creator (:email "private@example.com") :htmlLink "https://example.com/private"
                   :status "confirmed" :start (:dateTime "2026-10-09T19:00:00-03:00" :timeZone "America/Sao_Paulo")
                   :end (:dateTime "2026-10-09T20:00:00-03:00" :timeZone "America/Sao_Paulo"))))
    (with-temp-buffer
      (my/org-calendar-auto--insert-comparison local remote "This event")
      (let ((text (buffer-string)))
        (should (string-match-p "1 changed field" text))
        (should (string-match-p "Title\n  Org: +Sextou offline\n  Google: +Sextou online" text))
        (should (string-match-p "When: .*UTC" text))
        (should-not (string-match-p "When\n" text))
        (should-not (string-match-p "private-event-id\\|private-etag\\|private@example\\|htmlLink\\|dateTime\\|creator" text))))))

(ert-deftest my/calendar-review-all-day-end-is-inclusive-and-multiline-text-is-readable ()
  (let* ((local '((summary . "Trip") (start . ((date . "2026-10-12"))) (end . ((date . "2026-10-15")))
                  (description . "First line\nSecond line") (location . "Home") (status . "confirmed")))
         (remote (my/calendar-test-event
                  '((summary . "Trip") (start . ((date . "2026-10-12"))) (end . ((date . "2026-10-15")))
                    (description . "") (location . "Office") (status . "confirmed")) "id" "etag")))
    (with-temp-buffer
      (my/org-calendar-auto--insert-comparison local remote "This event")
      (let ((text (buffer-string)))
        (should (string-match-p "2026-10-12 to 2026-10-14 (all day; includes final day)" text))
        (should (string-match-p "2 changed fields" text))
        (should (string-match-p "First line\n +Second line" text))
        (should (string-match-p "Google: +(empty)" text))))))

(ert-deftest my/calendar-review-deleted-google-event-does-not-show-spurious-empty-fields ()
  (let ((local '((summary . "Local edit") (start . ((date . "2026-10-12")))
                 (end . ((date . "2026-10-13"))) (status . "confirmed"))))
    (dolist (remote '(nil (:id "id" :status "cancelled")))
      (with-temp-buffer
        (my/org-calendar-auto--insert-comparison local remote "This event")
        (should (string-match-p "Google deleted or cancelled" (buffer-string)))
        (should (string-match-p "Status\n  Org: +Active\n  Google: +Deleted in Google" (buffer-string)))
        (should-not (string-match-p "Title\n\\|Description\n" (buffer-string)))))))

(ert-deftest my/calendar-review-occurrence-cancellation-keeps-local-time-and-explicit-status ()
  (let* ((remote '(:summary "Weekly event" :status "confirmed" :start (:date "2026-10-12") :end (:date "2026-10-13")))
         (local (plist-put (copy-tree remote) :status "cancelled")))
    (with-temp-buffer
      (my/org-calendar-auto--insert-comparison local remote "This occurrence only")
      (should (string-match-p "Scope: This occurrence only" (buffer-string)))
      (should (string-match-p "When: 2026-10-12 (all day)" (buffer-string)))
      (should (string-match-p "Status\n  Org: +Cancelled\n  Google: +Active" (buffer-string))))))

(ert-deftest my/calendar-review-buttons-still-resolve-the-existing-conflict ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Original")))
      (my/org-calendar-auto--start)
      (org-with-point-at marker (org-edit-headline "Org choice") (save-buffer))
      (let* ((event (car (hash-table-values my/calendar-test-server))) (id (plist-get event :id)))
        (puthash id (plist-put (plist-put (copy-tree event) :summary "Google choice") :etag "google-v2") my/calendar-test-server))
      (my/org-calendar-auto--start)
      (save-window-excursion
        (my/org-calendar-auto-review)
        (with-current-buffer "*Personal Calendar Sync*"
          (should (string-match-p "1 changed field" (buffer-string)))
          (should (string-match-p "Update Google with the Org version" (buffer-string)))
          (goto-char (point-min)) (search-forward "Keep Org")
          (button-activate (button-at (1- (point))))))
      (org-with-point-at marker
        (should (equal (org-entry-get nil "GCAL_AUTO_RESOLUTION") "org"))
        (should (equal (org-entry-get nil "GCAL_AUTO_RESOLUTION_HASH")
                       (my/org-calendar-auto--hash (my/org-calendar-auto--local-payload)))))
      (my/org-calendar-auto--start)
      (org-with-point-at marker
        (ert-info ((format "Saved record: %S; sync: %S; calls: %S"
                           (my/org-calendar-auto--record) my/org-calendar-auto-status my/calendar-test-calls))
          (should-not (org-entry-get nil "GCAL_AUTO_CONFLICT"))))
      (should (equal (plist-get (car (hash-table-values my/calendar-test-server)) :summary) "Org choice")))))

(ert-deftest my/calendar-review-occurrence-diff-preserves-the-stale-choice-guard ()
  (my/calendar-test-workspace
    (let* ((event '(:id "instance" :summary "Old" :status "confirmed"
                    :start (:date "2026-10-12") :end (:date "2026-10-13")))
           (desired (plist-put (copy-tree event) :summary "Org version"))
           (remote (plist-put (copy-tree event) :summary "Google version"))
           (job (list :id "instance" :desired desired :conflict remote)))
      (setq my/org-calendar-repeat--pending (list job))
      (with-temp-buffer
        (my/org-calendar-repeat-review)
        (should (string-match-p "1 changed field" (buffer-string)))
        (should (string-match-p "leave the series unchanged" (buffer-string)))
        (goto-char (point-min)) (search-forward "Keep Org occurrence")
        (let ((button (button-at (1- (point)))))
          (setq my/org-calendar-repeat--pending (list (plist-put (copy-tree job) :desired event)))
          (should-error (button-activate button) :type 'user-error))))))

(defun my/calendar-restore-test-conflict (&optional missing)
  "Make a saved Org rename conflict with Google deletion; return its marker."
  (let ((marker (my/calendar-test-heading "Original event")))
    (my/org-calendar-auto--start)
    (org-with-point-at marker
      (org-edit-headline "Recovered Org title")
      (goto-char (nth 1 (my/org-calendar-auto--drawer)))
      (insert "\nPrivate local note\n")
      (save-buffer))
    (let* ((event (car (hash-table-values my/calendar-test-server))) (id (plist-get event :id)))
      (if missing (remhash id my/calendar-test-server)
        (puthash id (list :id id :status "cancelled" :etag "deleted-v2") my/calendar-test-server)))
    (my/org-calendar-auto--start)
    marker))

(defun my/calendar-restore-test-choose (marker)
  "Explicitly approve restoration of MARKER's current conflict."
  (let ((record (org-with-point-at marker (my/org-calendar-auto--record))))
    (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
      (my/org-calendar-auto--queue-restore marker (plist-get record :id) (plist-get record :hash)
                                           (plist-get record :conflict)))))

(ert-deftest my/calendar-restore-new-id-preserves-org-data-notes-and-deleted-history ()
  (my/calendar-test-workspace
    (let* ((marker (my/calendar-restore-test-conflict))
           (old-id (org-with-point-at marker (org-entry-get nil "GCAL_AUTO_ID"))))
      (my/calendar-restore-test-choose marker)
      (my/org-calendar-auto--start)
      (org-with-point-at marker
        (let* ((id (org-entry-get nil "GCAL_AUTO_ID")) (event (gethash id my/calendar-test-server)))
          (should-not (equal id old-id))
          (should (equal (org-entry-get nil "GCAL_AUTO_RESTORED_FROM") old-id))
          (should (equal (plist-get event :summary) "Recovered Org title"))
          (should (equal (plist-get event :status) "confirmed"))
          (should (equal (org-entry-get nil "entry-id") (org-gcal--format-entry-id my/org-calendar-auto--calendar id)))
          (should-not (org-entry-get nil "GCAL_AUTO_CONFLICT"))
          (should (string-match-p "Private local note" (buffer-string)))
          (should (equal (plist-get (my/org-calendar-auto--decode (org-entry-get nil "GCAL_AUTO_PREVIOUS")) :deleted-id) old-id))))
      (should (equal (plist-get (gethash old-id my/calendar-test-server) :status) "cancelled"))
      (should-not (seq-some (lambda (call) (and (equal (nth 1 call) old-id) (member (car call) '("PATCH" "DELETE"))))
                            my/calendar-test-calls))
      (my/org-calendar-auto--start)
      (should (equal my/org-calendar-auto-status "up to date")))))

(ert-deftest my/calendar-restore-missing-google-event-can-be-recreated ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-restore-test-conflict t)))
      (my/calendar-restore-test-choose marker)
      (my/org-calendar-auto--start)
      (should (= (hash-table-count my/calendar-test-server) 1))
      (should (equal (plist-get (car (hash-table-values my/calendar-test-server)) :summary) "Recovered Org title")))))

(ert-deftest my/calendar-restore-cannot-run-from-stale-review-or-after-declining ()
  (my/calendar-test-workspace
    (let* ((marker (my/calendar-restore-test-conflict))
           (record (org-with-point-at marker (my/org-calendar-auto--record))) prompts)
      (setq my/calendar-test-calls nil)
      (cl-letf (((symbol-function 'yes-or-no-p)
                 (lambda (prompt)
                   (push prompt prompts)
                   (should (string-match-p "NEW Google event" prompt))
                   (should (string-match-p "without old invitations or reminders" prompt))
                   nil)))
        (should-error (my/org-calendar-auto--queue-restore marker (plist-get record :id) (plist-get record :hash)
                                                         (plist-get record :conflict)) :type 'user-error))
      (should (= (length prompts) 1))
      (org-with-point-at marker (should-not (org-entry-get nil "GCAL_AUTO_RESOLUTION"))
        (org-edit-headline "Newer local rename") (save-buffer))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) (ert-fail "Stale review must be rejected before confirmation"))))
        (should-error (my/org-calendar-auto--queue-restore marker (plist-get record :id) (plist-get record :hash)
                                                         (plist-get record :conflict)) :type 'user-error))
      (should-not (seq-some (lambda (call) (equal (car call) "POST")) my/calendar-test-calls)))))

(ert-deftest my/calendar-restore-rechecks-local-edits-made-during-confirmation ()
  (my/calendar-test-workspace
    (let* ((marker (my/calendar-restore-test-conflict))
           (record (org-with-point-at marker (my/org-calendar-auto--record))))
      (cl-letf (((symbol-function 'yes-or-no-p)
                 (lambda (&rest _)
                   (org-with-point-at marker (org-edit-headline "Changed while confirming") (save-buffer)) t)))
        (should-error (my/org-calendar-auto--queue-restore marker (plist-get record :id) (plist-get record :hash)
                                                         (plist-get record :conflict)) :type 'user-error))
      (org-with-point-at marker (should-not (org-entry-get nil "GCAL_AUTO_RESOLUTION"))))))

(ert-deftest my/calendar-restore-newer-google-version-or-local-edit-invalidates-approved-choice ()
  (my/calendar-test-workspace
    (let* ((marker (my/calendar-restore-test-conflict))
           (old-id (org-with-point-at marker (org-entry-get nil "GCAL_AUTO_ID"))))
      (my/calendar-restore-test-choose marker)
      (puthash old-id (plist-put (gethash old-id my/calendar-test-server) :etag "newer-deletion") my/calendar-test-server)
      (setq my/calendar-test-calls nil)
      (my/org-calendar-auto--start)
      (should-not (seq-some (lambda (call) (equal (car call) "POST")) my/calendar-test-calls))
      (org-with-point-at marker (should-not (org-entry-get nil "GCAL_AUTO_RESOLUTION")))
      (my/calendar-restore-test-choose marker)
      (org-with-point-at marker (org-edit-headline "Newer Org edit") (save-buffer))
      (my/org-calendar-auto--start)
      (should-not (seq-some (lambda (call) (equal (car call) "POST")) my/calendar-test-calls))
      (org-with-point-at marker (should (equal (org-entry-get nil "GCAL_AUTO_ID") old-id))))))

(ert-deftest my/calendar-restore-offline-and-lost-reply-retries-create-exactly-one-copy ()
  (my/calendar-test-workspace
    (let* ((marker (my/calendar-restore-test-conflict))
           (old-id (org-with-point-at marker (org-entry-get nil "GCAL_AUTO_ID")))
           (adapter (symbol-function 'my/calendar-test-request)))
      (my/calendar-restore-test-choose marker)
      (cl-letf (((symbol-function 'my/org-calendar-auto--request)
                 (lambda (method id payload etag callback &optional params)
                   (if (equal method "POST") (funcall callback nil nil)
                     (funcall adapter method id payload etag callback params)))))
        (my/org-calendar-auto--start))
      (let ((new-id (org-with-point-at marker (org-entry-get nil "GCAL_AUTO_ID"))))
        (should-not (equal new-id old-id))
        (org-with-point-at marker (should-not (org-entry-get nil "entry-id")))
        (setq my/calendar-test-lost-reply t)
        (my/org-calendar-auto--start)
        (my/org-calendar-auto--start)
        (org-with-point-at marker (should (equal (org-entry-get nil "GCAL_AUTO_ID") new-id)))
        (should (= (hash-table-count my/calendar-test-server) 2))
        (should (= (cl-count "POST" my/calendar-test-calls :key #'car :test #'equal) 2))
        (should (equal my/org-calendar-auto-status "up to date"))))))

(ert-deftest my/calendar-restore-accepting-deletion-still-retains-heading-and-notes ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-restore-test-conflict)))
      (my/org-calendar-auto--resolve marker "google")
      (setq my/calendar-test-calls nil)
      (my/org-calendar-auto--start)
      (org-with-point-at marker
        (should (equal (org-get-todo-state) "CANCELLED"))
        (should (equal (org-get-heading t t t t) "Recovered Org title"))
        (should (string-match-p "Private local note" (buffer-string))))
      (should-not (seq-some (lambda (call) (equal (car call) "POST")) my/calendar-test-calls)))))

(ert-deftest my/calendar-restore-review-offers-both-explicit-deletion-choices ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-restore-test-conflict)))
      (save-window-excursion
        (my/org-calendar-auto-review)
        (with-current-buffer "*Personal Calendar Sync*"
          (should (string-match-p "Restore as a new Google event" (buffer-string)))
          (should (string-match-p "Accept Google deletion" (buffer-string)))
          (goto-char (point-min)) (search-forward "Restore as a new Google event")
          (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
            (button-activate (button-at (1- (point)))))))
      (org-with-point-at marker (should (equal (org-entry-get nil "GCAL_AUTO_RESOLUTION") "restore"))))))

(ert-deftest my/calendar-restore-series-recreation-warns-about-exceptions-and-can-retry-offline ()
  (my/calendar-test-workspace
    (my/calendar-repeat-test-seed)
    (my/org-calendar-auto--start)
    (let ((marker (my/org-calendar-repeat--series-marker "series"))
          (adapter (symbol-function 'my/calendar-test-request)))
      (org-with-point-at marker (org-edit-headline "Recovered series") (save-buffer))
      (puthash "series" '(:id "series" :status "cancelled" :etag "deleted-v2") my/calendar-test-server)
      (my/org-calendar-auto--start)
      (let ((record (org-with-point-at marker (my/org-calendar-auto--record))))
        (cl-letf (((symbol-function 'yes-or-no-p)
                   (lambda (prompt)
                     (should (string-match-p "whole series" prompt))
                     (should (string-match-p "without old moved/skipped exceptions" prompt))
                     t)))
          (my/org-calendar-auto--queue-restore marker (plist-get record :id) (plist-get record :hash)
                                               (plist-get record :conflict))))
      (cl-letf (((symbol-function 'my/org-calendar-auto--request)
                 (lambda (method id payload etag callback &optional params)
                   (if (equal method "POST") (funcall callback nil nil)
                     (funcall adapter method id payload etag callback params)))))
        (my/org-calendar-auto--start))
      (org-with-point-at marker (should (org-entry-get nil "GCAL_SERIES_APPROVED")))
      (my/org-calendar-auto--start)
      (org-with-point-at marker
        (let* ((id (org-entry-get nil "GCAL_AUTO_ID")) (event (gethash id my/calendar-test-server)))
          (should-not (equal id "series"))
          (should (equal (plist-get event :summary) "Recovered series"))
          (should (equal (plist-get event :recurrence) '("RRULE:FREQ=DAILY")))
          (should-not (org-entry-get nil "GCAL_SERIES_APPROVED")))))))

(ert-deftest my/calendar-restore-will-not-clone-an-event-google-revived-after-confirmation ()
  (my/calendar-test-workspace
    (let* ((marker (my/calendar-restore-test-conflict))
           (record (org-with-point-at marker (my/org-calendar-auto--record)))
           (old-id (plist-get record :id)))
      (my/calendar-restore-test-choose marker)
      (puthash old-id (my/calendar-test-event (plist-get record :payload) old-id "revived-v3") my/calendar-test-server)
      (setq my/calendar-test-calls nil)
      (my/org-calendar-auto--start)
      (should-not (seq-some (lambda (call) (equal (car call) "POST")) my/calendar-test-calls))
      (org-with-point-at marker (should (equal (org-entry-get nil "GCAL_AUTO_ID") old-id))))))

(ert-deftest my/calendar-auto-identical-calendar-path-does-not-depend-on-filesystem-identity ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Saved personal event")))
      (cl-letf (((symbol-function 'file-equal-p) (lambda (&rest _) nil)))
        (should (my/org-calendar-auto--safe-marker marker))
        (should (my/org-calendar-auto--same-file-p my/org-calendar-auto--file))
        (should-not (my/org-calendar-auto--same-file-p (my/org-file "calendar-work.org")))
        (should-not (my/org-calendar-auto--same-file-p
                     (expand-file-name "other/calendar-personal.org" org-directory)))))))

(ert-deftest my/calendar-auto-alias-path-still-requires-physical-file-identity ()
  (my/calendar-test-workspace
    (let ((alias (expand-file-name "personal-calendar-alias.org" org-directory)))
      (make-symbolic-link my/org-calendar-auto--file alias)
      (should (my/org-calendar-auto--same-file-p alias))
      (should-not (my/org-calendar-auto--same-file-p (my/org-file "calendar-work.org"))))))

(ert-deftest my/calendar-auto-google-choice-revives-cancelled-event-without-closed-stamp ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Original event")))
      (my/org-calendar-auto--start)
      (let* ((event (car (hash-table-values my/calendar-test-server))) (id (plist-get event :id)))
        (org-with-point-at marker
          (let ((org-log-done 'time)) (org-todo "CANCELLED"))
          (should (org-entry-get nil "CLOSED"))
          (goto-char (nth 1 (my/org-calendar-auto--drawer)))
          (insert "\n:LOGBOOK:\n- Historical note [2026-10-09 Fri 12:00]\n:END:\nPrivate note\n")
          (save-buffer))
        (puthash id (plist-put (plist-put (copy-tree event) :summary "Google kept event") :etag "google-v2") my/calendar-test-server)
        (my/org-calendar-auto--start)
        (org-with-point-at marker (should (org-entry-get nil "GCAL_AUTO_CONFLICT")))
        (my/org-calendar-auto--resolve marker "google")
        (my/org-calendar-auto--start)
        (org-with-point-at marker
          (should-not (org-get-todo-state))
          (should-not (org-entry-get nil "CLOSED"))
          (should (equal (org-get-heading t t t t) "Google kept event"))
          (should (string-match-p "Historical note \\[2026-10-09 Fri 12:00\\]" (buffer-string)))
          (should (string-match-p "Private note" (buffer-string)))
          (should-not (org-entry-get nil "GCAL_AUTO_CONFLICT")))
        (should (equal org-log-done 'time))))))

(ert-deftest my/calendar-auto-still-cancelled-event-retains-its-closed-stamp ()
  (my/calendar-test-workspace
    (let ((marker (my/calendar-test-heading "Cancelled event")))
      (my/org-calendar-auto--start)
      (org-with-point-at marker
        (let ((org-log-done 'time)) (org-todo "CANCELLED"))
        (save-buffer)
        (let ((closed (org-entry-get nil "CLOSED")))
          (my/org-calendar-auto--import (org-entry-get nil "GCAL_AUTO_ID") '(:status "cancelled"))
          (should (equal (org-get-todo-state) "CANCELLED"))
          (should (equal (org-entry-get nil "CLOSED") closed)))))))

(ert-deftest my/calendar-auto-cancellation-stamp-cleanup-does-not-change-task-logging ()
  (my/calendar-test-workspace
    (with-current-buffer (find-file-noselect (my/org-file "work.org"))
      (goto-char (point-max)) (insert "\n* TODO Work task\n") (org-back-to-heading t)
      (let ((org-log-done 'time))
        (org-todo "CANCELLED")
        (should (org-entry-get nil "CLOSED"))
        (org-todo "TODO")
        (should-not (org-entry-get nil "CLOSED"))
        (should (equal org-log-done 'time))))))
